# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\EP\ELEE_2\UI\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from menu import Ui_MenwWindow
import mysql.connector



        
class Ui_Login(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MenwWindow()
        self.ui.setupUi(self.window)
        Login.hide()
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 221)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 20, 181, 19))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 50, 244, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(self.layoutWidget)
        self.username.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 1, 1, 1)
      
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.login = QtWidgets.QPushButton(self.layoutWidget)
        self.login.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
       
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Please Login to Security Duty"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "username"))
        self.label_2.setText(_translate("MainWindow", "password"))

        self.login.clicked.connect(self.loginfunc)
    

    def loginfunc(self):
        
        username = self.username.text()
        password = self.password.text()
        user(username, password, self)
   

def ConnectorMysql():
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="12341234",
        database="testdb",
        # auth_plugin='mysql_native_password'
    )
    print('Connect Database Successful')
    return mydb

def user(username,password,self):
    print(password)
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT `pass` FROM `user` WHERE `user`="{username}"'
    cur.execute(sql)
    myresult = cur.fetchall()
    print(myresult)
    
    if myresult != []:
        x = str(myresult[0][0])
        passwd = password
        
        if passwd == x:
            print("login")
            self.openWindow()
        else:
            print("fail") 
            msg = QMessageBox()
            msg.setText('Incorrect Password')
            msg.exec_()
    else:
        msg = QMessageBox()
        msg.setText('Incorrect Password')
        msg.exec_()        
    return 



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())